###> Get all user
GET http://localhost:8080/users/

###> Get user
GET http://localhost:8080/users/1000

###> Register user
POST http://localhost:8080/users/
Content-Type: application/json

{
    "name": "John",
    "email": "test2@gmail.com",
    "password": "password",
    "confirmPassword": "password",
    "phoneNumber": "1231232548",
    "address": "243 Le Hong Phong Str",
    "dob": "01/01/2000",
    "gender": "Male",
    "avatarUrl": "http://localhost:8080/users/1000",
    "roleId": "2"
}

###> Update user
PUT http://localhost:8080/users/1004
Content-Type: application/json

{
    "name": "John",
    "email": "update@gmail.com",
    "phoneNumber": "123122332548",
    "address": "243 Le Hong Phong Str",
    "dob": "01/01/2000",
    "gender": "Male",
    "avatarUrl": "http://localhost:8080/users/Ahihihoho"
}


###> Delete user
DELETE http://localhost:8080/users/1006
Content-Type: application/json

###> Ban user
PUT http://localhost:8080/users/ban/1004
Content-Type: application/json

###> Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "admin1",
    "password": "1"
}

###> Search with token
GET http://localhost:8080/users/search?name=ab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjEiLCJpYXQiOjE3MTIxOTkyNDEsImV4cCI6MTcxMjIwNDI0MX0.2Ky4f43OI_EBwJcQgxsbxRGSgckHf7Dp_y5ttmgPt8liCG1WoBv8IDKY9sW11C8IpAqAOIQetYBRtZtbhom-cw

###> Search without token
GET http://localhost:8080/users/search?name=ab
Content-Type: application/json
